DECLARE
    CURSOR Cur_saldos_diarios
    IS
    SELECT b.Nivel_1, b.Nivel_2,  b.Nivel_3,  b.Nivel_4,
           b.Nivel_5, b.Nivel_6,  b.Nivel_7,  b.Nivel_8, a.codigo_empresa,
           sum(nvl(Cantidad_Db_Dia_1,0)) Cantidad_Db_Dia_1,
       sum(nvl(Cantidad_Db_Dia_2,0)) Cantidad_Db_Dia_2,
       sum(nvl(Cantidad_Db_Dia_3,0)) Cantidad_Db_Dia_3,  
       sum(nvl(Cantidad_Db_Dia_4,0)) Cantidad_Db_Dia_4,  
      sum(nvl(Cantidad_Db_Dia_5,0)) Cantidad_Db_Dia_5,   
        sum(nvl(Cantidad_Db_Dia_6,0)) Cantidad_Db_Dia_6,  
        sum(nvl(Cantidad_Db_Dia_7,0)) Cantidad_Db_Dia_7,  
        sum(nvl(Cantidad_Db_Dia_8,0)) Cantidad_Db_Dia_8,  
        sum(nvl(Cantidad_Db_Dia_9,0)) Cantidad_Db_Dia_9,  
        sum(nvl(Cantidad_Db_Dia_10,0)) Cantidad_Db_Dia_10, 
        sum(nvl(Cantidad_Db_Dia_11,0)) Cantidad_Db_Dia_11, 
        sum(nvl(Cantidad_Db_Dia_12,0)) Cantidad_Db_Dia_12, 
        sum(nvl(Cantidad_Db_Dia_13,0)) Cantidad_Db_Dia_13, 
        sum(nvl(Cantidad_Db_Dia_14,0)) Cantidad_Db_Dia_14, 
      sum(nvl(Cantidad_Db_Dia_15,0)) Cantidad_Db_Dia_15, 
        sum(nvl(Cantidad_Db_Dia_16,0)) Cantidad_Db_Dia_16, 
        sum(nvl(Cantidad_Db_Dia_17,0)) Cantidad_Db_Dia_17, 
        sum(nvl(Cantidad_Db_Dia_18,0)) Cantidad_Db_Dia_18, 
        sum(nvl(Cantidad_Db_Dia_19,0)) Cantidad_Db_Dia_19, 
        sum(nvl(Cantidad_Db_Dia_20,0)) Cantidad_Db_Dia_20, 
        sum(nvl(Cantidad_Db_Dia_21,0)) Cantidad_Db_Dia_21, 
        sum(nvl(Cantidad_Db_Dia_22,0)) Cantidad_Db_Dia_22, 
        sum(nvl(Cantidad_Db_Dia_23,0)) Cantidad_Db_Dia_23, 
        sum(nvl(Cantidad_Db_Dia_24,0)) Cantidad_Db_Dia_24, 
      sum(nvl(Cantidad_Db_Dia_25,0)) Cantidad_Db_Dia_25, 
        sum(nvl(Cantidad_Db_Dia_26,0)) Cantidad_Db_Dia_26, 
        sum(nvl(Cantidad_Db_Dia_27,0)) Cantidad_Db_Dia_27, 
        sum(nvl(Cantidad_Db_Dia_28,0)) Cantidad_Db_Dia_28, 
        sum(nvl(Cantidad_Db_Dia_29,0)) Cantidad_Db_Dia_29, 
        sum(nvl(cantidad_Db_Dia_30,0)) Cantidad_Db_Dia_30, 
        sum(nvl(Cantidad_Db_Dia_31,0)) Cantidad_Db_Dia_31,
        sum(nvl(Total_Db_Dia_1,0)) Total_Db_Dia_1,
        sum(nvl(Total_Db_Dia_2,0)) Total_Db_Dia_2, 
        sum(nvl(Total_Db_Dia_3,0)) Total_Db_Dia_3, 
        sum(nvl(Total_Db_Dia_4,0)) Total_Db_Dia_4, 
      sum(nvl(Total_Db_Dia_5,0))  Total_Db_Dia_5,
        sum(nvl(Total_Db_Dia_6,0))  Total_Db_Dia_6,
        sum(nvl(Total_Db_Dia_7,0))  Total_Db_Dia_7,
        sum(nvl(Total_Db_Dia_8,0))  Total_Db_Dia_8,
        sum(nvl(Total_Db_Dia_9,0))  Total_Db_Dia_9,
        sum(nvl(Total_Db_Dia_10,0)) Total_Db_Dia_10,
        sum(nvl(Total_Db_Dia_11,0)) Total_Db_Dia_11, 
        sum(nvl(Total_Db_Dia_12,0)) Total_Db_Dia_12,
        sum(nvl(Total_Db_Dia_13,0)) Total_Db_Dia_13,
        sum(nvl(Total_Db_Dia_14,0)) Total_Db_Dia_14,
      sum(nvl(Total_Db_Dia_15,0))  Total_Db_Dia_15,
        sum(nvl(Total_Db_Dia_16,0)) Total_Db_Dia_16,
        sum(nvl(Total_Db_Dia_17,0)) Total_Db_Dia_17,
        sum(nvl(Total_Db_Dia_18,0)) Total_Db_Dia_18,
        sum(nvl(Total_Db_Dia_19,0)) Total_Db_Dia_19,
        sum(nvl(Total_Db_Dia_20,0)) Total_Db_Dia_20,
        sum(nvl(Total_Db_Dia_21,0)) Total_Db_Dia_21,
        sum(nvl(Total_Db_Dia_22,0)) Total_Db_Dia_22,
        sum(nvl(Total_Db_Dia_23,0)) Total_Db_Dia_23,
        sum(nvl(Total_Db_Dia_24,0)) Total_Db_Dia_24,
      sum(nvl(Total_Db_Dia_25,0)) Total_Db_Dia_25,
        sum(nvl(Total_Db_Dia_26,0)) Total_Db_Dia_26,
        sum(nvl(Total_Db_Dia_27,0)) Total_Db_Dia_27,
        sum(nvl(Total_Db_Dia_28,0)) Total_Db_Dia_28,
        sum(nvl(Total_Db_Dia_29,0)) Total_Db_Dia_29,
        sum(nvl(Total_Db_Dia_30,0)) Total_Db_Dia_30,
        sum(nvl(Total_Db_Dia_31,0)) Total_Db_Dia_31,
      sum(nvl(Cantidad_Cr_Dia_1,0)) Cantidad_Cr_Dia_1,
       sum(nvl(Cantidad_Cr_Dia_2,0)) Cantidad_Cr_Dia_2,
       sum(nvl(Cantidad_Cr_Dia_3,0)) Cantidad_Cr_Dia_3,  
       sum(nvl(Cantidad_Cr_Dia_4,0)) Cantidad_Cr_Dia_4,  
      sum(nvl(Cantidad_Cr_Dia_5,0)) Cantidad_Cr_Dia_5,   
        sum(nvl(Cantidad_Cr_Dia_6,0)) Cantidad_Cr_Dia_6,  
        sum(nvl(Cantidad_Cr_Dia_7,0)) Cantidad_Cr_Dia_7,  
        sum(nvl(Cantidad_Cr_Dia_8,0)) Cantidad_Cr_Dia_8,  
        sum(nvl(Cantidad_Cr_Dia_9,0)) Cantidad_Cr_Dia_9,  
        sum(nvl(Cantidad_Cr_Dia_10,0)) Cantidad_Cr_Dia_10, 
        sum(nvl(Cantidad_Cr_Dia_11,0)) Cantidad_Cr_Dia_11, 
        sum(nvl(Cantidad_Cr_Dia_12,0)) Cantidad_Cr_Dia_12, 
        sum(nvl(Cantidad_Cr_Dia_13,0)) Cantidad_Cr_Dia_13, 
        sum(nvl(Cantidad_Cr_Dia_14,0)) Cantidad_Cr_Dia_14, 
      sum(nvl(Cantidad_Cr_Dia_15,0)) Cantidad_Cr_Dia_15, 
        sum(nvl(Cantidad_Cr_Dia_16,0)) Cantidad_Cr_Dia_16, 
        sum(nvl(Cantidad_Cr_Dia_17,0)) Cantidad_Cr_Dia_17, 
        sum(nvl(Cantidad_Cr_Dia_18,0)) Cantidad_Cr_Dia_18, 
        sum(nvl(Cantidad_Cr_Dia_19,0)) Cantidad_Cr_Dia_19, 
        sum(nvl(Cantidad_Cr_Dia_20,0)) Cantidad_Cr_Dia_20, 
        sum(nvl(Cantidad_Cr_Dia_21,0)) Cantidad_Cr_Dia_21, 
        sum(nvl(Cantidad_Cr_Dia_22,0)) Cantidad_Cr_Dia_22, 
        sum(nvl(Cantidad_Cr_Dia_23,0)) Cantidad_Cr_Dia_23, 
        sum(nvl(Cantidad_Cr_Dia_24,0)) Cantidad_Cr_Dia_24, 
      sum(nvl(Cantidad_Cr_Dia_25,0)) Cantidad_Cr_Dia_25, 
        sum(nvl(Cantidad_Cr_Dia_26,0)) Cantidad_Cr_Dia_26, 
        sum(nvl(Cantidad_Cr_Dia_27,0)) Cantidad_Cr_Dia_27, 
        sum(nvl(Cantidad_Cr_Dia_28,0)) Cantidad_Cr_Dia_28, 
        sum(nvl(Cantidad_Cr_Dia_29,0)) Cantidad_Cr_Dia_29, 
        sum(nvl(cantidad_Cr_Dia_30,0)) Cantidad_Cr_Dia_30, 
        sum(nvl(Cantidad_Cr_Dia_31,0)) Cantidad_Cr_Dia_31,
        sum(nvl(Total_Cr_Dia_1,0)) Total_Cr_Dia_1,
        sum(nvl(Total_Cr_Dia_2,0)) Total_Cr_Dia_2, 
        sum(nvl(Total_Cr_Dia_3,0)) Total_Cr_Dia_3, 
        sum(nvl(Total_Cr_Dia_4,0)) Total_Cr_Dia_4, 
      sum(nvl(Total_Cr_Dia_5,0))  Total_Cr_Dia_5,
        sum(nvl(Total_Cr_Dia_6,0))  Total_Cr_Dia_6,
        sum(nvl(Total_Cr_Dia_7,0))  Total_Cr_Dia_7,
        sum(nvl(Total_Cr_Dia_8,0))  Total_Cr_Dia_8,
        sum(nvl(Total_Cr_Dia_9,0))  Total_Cr_Dia_9,
        sum(nvl(Total_Cr_Dia_10,0)) Total_Cr_Dia_10,
        sum(nvl(Total_Cr_Dia_11,0)) Total_Cr_Dia_11, 
        sum(nvl(Total_Cr_Dia_12,0)) Total_Cr_Dia_12,
        sum(nvl(Total_Cr_Dia_13,0)) Total_Cr_Dia_13,
        sum(nvl(Total_Cr_Dia_14,0)) Total_Cr_Dia_14,
      sum(nvl(Total_Cr_Dia_15,0))  Total_Cr_Dia_15,
        sum(nvl(Total_Cr_Dia_16,0)) Total_Cr_Dia_16,
        sum(nvl(Total_Cr_Dia_17,0)) Total_Cr_Dia_17,
        sum(nvl(Total_Cr_Dia_18,0)) Total_Cr_Dia_18,
        sum(nvl(Total_Cr_Dia_19,0)) Total_Cr_Dia_19,
        sum(nvl(Total_Cr_Dia_20,0)) Total_Cr_Dia_20,
        sum(nvl(Total_Cr_Dia_21,0)) Total_Cr_Dia_21,
        sum(nvl(Total_Cr_Dia_22,0)) Total_Cr_Dia_22,
        sum(nvl(Total_Cr_Dia_23,0)) Total_Cr_Dia_23,
        sum(nvl(Total_Cr_Dia_24,0)) Total_Cr_Dia_24,
      sum(nvl(Total_Cr_Dia_25,0)) Total_Cr_Dia_25,
        sum(nvl(Total_Cr_Dia_26,0)) Total_Cr_Dia_26,
        sum(nvl(Total_Cr_Dia_27,0)) Total_Cr_Dia_27,
        sum(nvl(Total_Cr_Dia_28,0)) Total_Cr_Dia_28,
        sum(nvl(Total_Cr_Dia_29,0)) Total_Cr_Dia_29,
        sum(nvl(Total_Cr_Dia_30,0)) Total_Cr_Dia_30,
        sum(nvl(Total_Cr_Dia_31,0)) Total_Cr_Dia_31,
    sum(nvl(a.saldo_acumulado_mensual,0))  saldo_acumulado_mensual, 
    sum(nvl(a.Saldo_Dia_Anterior_Calendario,0)) Saldo_Dia_Anterior_Calendario,
         sum(NVL(Saldo_Dia_1,0)) Saldo_Dia_1,
        sum(NVL(Saldo_Dia_2,0)) Saldo_Dia_2,
        sum(NVL(Saldo_Dia_3,0)) Saldo_Dia_3,
        sum(NVL(Saldo_Dia_4,0)) Saldo_Dia_4,
        sum(NVL(Saldo_Dia_5,0)) Saldo_Dia_5,
        sum(NVL(Saldo_Dia_6,0)) Saldo_Dia_6,
        sum(NVL(Saldo_Dia_7,0)) Saldo_Dia_7,
        sum(NVL(Saldo_Dia_8,0)) Saldo_Dia_8,
        sum(NVL(Saldo_Dia_9,0)) Saldo_Dia_9,
        sum(NVL(Saldo_Dia_10,0)) Saldo_Dia_10,
        sum(NVL(Saldo_Dia_11,0)) Saldo_Dia_11,
        sum(NVL(Saldo_Dia_12,0)) Saldo_Dia_12,
        sum(NVL(Saldo_Dia_13,0)) Saldo_Dia_13,
        sum(NVL(Saldo_Dia_14,0)) Saldo_Dia_14,
        sum(NVL(Saldo_Dia_15,0)) Saldo_Dia_15,
        sum(NVL(Saldo_Dia_16,0)) Saldo_Dia_16,
        sum(NVL(Saldo_Dia_17,0)) Saldo_Dia_17,
        sum(NVL(Saldo_Dia_18,0)) Saldo_Dia_18,
        sum(NVL(Saldo_Dia_19,0)) Saldo_Dia_19,
        sum(NVL(Saldo_Dia_20,0)) Saldo_Dia_20,
        sum(NVL(Saldo_Dia_21,0)) Saldo_Dia_21,
        sum(NVL(Saldo_Dia_22,0)) Saldo_Dia_22,
        sum(NVL(Saldo_Dia_23,0)) Saldo_Dia_23,
        sum(NVL(Saldo_Dia_24,0)) Saldo_Dia_24,
        sum(NVL(Saldo_Dia_25,0)) Saldo_Dia_25,
        sum(NVL(Saldo_Dia_26,0)) Saldo_Dia_26,
        sum(NVL(Saldo_Dia_27,0)) Saldo_Dia_27,
        sum(NVL(Saldo_Dia_28,0)) Saldo_Dia_28,
        sum(NVL(Saldo_Dia_29,0)) Saldo_Dia_29,
        sum(NVL(Saldo_Dia_30,0)) Saldo_Dia_30,
        sum(NVL(Saldo_Dia_31,0)) Saldo_Dia_31
        FROM   GM_CUENTAS_SUMARIAS b,
           GM_saldos_diarios  a,
         GM_TIPOS_DE_CUENTAS c, GM_BALANCE_CUENTAS  d,
         GM_BALANCE_CUENTAS  f,
         GM_TIPOS_DE_CUENTAS e
    WHERE b.cuenta_hasta >= a.nivel_1||a.nivel_2||a.nivel_3||a.nivel_4||a.nivel_5||
                  a.nivel_6||a.nivel_7||a.nivel_8
    AND   b.cuenta_desde <= a.nivel_1||a.nivel_2||a.nivel_3||a.nivel_4||a.nivel_5||
                  a.nivel_6||a.nivel_7||a.nivel_8
    and a.mes = 01
    and a.anio = 2011
    AND   b.codigo_empresa = 1
  AND  d.cuenta = b.nivel_1||b.nivel_2||b.nivel_3||b.nivel_4||b.nivel_5||
                  b.nivel_6||b.nivel_7||b.nivel_8
  AND  f.cuenta = a.nivel_1||a.nivel_2||a.nivel_3||a.nivel_4||a.nivel_5||
                  a.nivel_6||a.nivel_7||a.nivel_8
  AND   f.Codigo_Empresa = b.Codigo_Empresa
    AND   f.recibe_movimiento  = 'S'
    AND  f.codigo_tipo = c.codigo_tipo                
    AND  e.codigo_tipo = d.codigo_tipo
    group by b.Nivel_1, b.Nivel_2,  b.Nivel_3,  b.Nivel_4,
             b.Nivel_5, b.Nivel_6,  b.Nivel_7,  b.Nivel_8, a.codigo_empresa;
    
    Ln_AnioBase   number := 2011;
    Ln_MesBase    number := 01;
    Lv_Cuenta           Varchar2(32);
  BEGIN
    /******
            Sumarizacion para saldos diarios
     ******/
    FOR I IN Cur_saldos_diarios LOOP
     Lv_Cuenta := I.nivel_1||I.nivel_2||I.nivel_3||I.nivel_4||
                  I.nivel_5||I.nivel_6||I.nivel_7||I.nivel_8;
               UPDATE GM_SALDOS_DIARIOS
       SET saldo_acumulado_mensual = I.saldo_acumulado_mensual,
           Saldo_Dia_1  = I.Saldo_Dia_1,
           Saldo_Dia_2  = I.Saldo_Dia_2,
           Saldo_Dia_3  = I.Saldo_Dia_3,
           Saldo_Dia_4  = I.Saldo_Dia_4,
           Saldo_Dia_5  = I.Saldo_Dia_5,
           Saldo_Dia_6  = I.Saldo_Dia_6,
           Saldo_Dia_7  = I.Saldo_Dia_7,
           Saldo_Dia_8  = I.Saldo_Dia_8,
           Saldo_Dia_9  = I.Saldo_Dia_9,
           Saldo_Dia_10 = I.Saldo_Dia_10,
           Saldo_Dia_11 = I.Saldo_Dia_11,
           Saldo_Dia_12 = I.Saldo_Dia_12,
           Saldo_Dia_13 = I.Saldo_Dia_13,
           Saldo_Dia_14 = I.Saldo_Dia_14,
           Saldo_Dia_15 = I.Saldo_Dia_15,
           Saldo_Dia_16 = I.Saldo_Dia_16,
           Saldo_Dia_17 = I.Saldo_Dia_17,
           Saldo_Dia_18 = I.Saldo_Dia_18,
           Saldo_Dia_19 = I.Saldo_Dia_19,
           Saldo_Dia_20 = I.Saldo_Dia_20,
           Saldo_Dia_21 = I.Saldo_Dia_21,
           Saldo_Dia_22 = I.Saldo_Dia_22,
           Saldo_Dia_23 = I.Saldo_Dia_23,
           Saldo_Dia_24 = I.Saldo_Dia_24,
           Saldo_Dia_25 = I.Saldo_Dia_25,
           Saldo_Dia_26 = I.Saldo_Dia_26,
           Saldo_Dia_27 = I.Saldo_Dia_27,
           Saldo_Dia_28 = I.Saldo_Dia_28,
           Saldo_Dia_29 = I.Saldo_Dia_29,
           Saldo_Dia_30 = I.Saldo_Dia_30,
           Saldo_Dia_31 = I.Saldo_Dia_31,
        Cantidad_Db_Dia_1  = I.Cantidad_Db_Dia_1,
           Cantidad_Db_Dia_2  = I.Cantidad_Db_Dia_2,
           Cantidad_Db_Dia_3  = I.Cantidad_Db_Dia_3,
           Cantidad_Db_Dia_4  = I.Cantidad_Db_Dia_4,
           Cantidad_Db_Dia_5  = I.Cantidad_Db_Dia_5,
           Cantidad_Db_Dia_6  = I.Cantidad_Db_Dia_6,
           Cantidad_Db_Dia_7  = I.Cantidad_Db_Dia_7,
           Cantidad_Db_Dia_8  = I.Cantidad_Db_Dia_8,
           Cantidad_Db_Dia_9  = I.Cantidad_Db_Dia_9,
           Cantidad_Db_Dia_10 = I.Cantidad_Db_Dia_10,
           Cantidad_Db_Dia_11 = I.Cantidad_Db_Dia_11,
           Cantidad_Db_Dia_12 = I.Cantidad_Db_Dia_12,
           Cantidad_Db_Dia_13 = I.Cantidad_Db_Dia_13,
           Cantidad_Db_Dia_14 = I.Cantidad_Db_Dia_14,
           Cantidad_Db_Dia_15 = I.Cantidad_Db_Dia_15,
           Cantidad_Db_Dia_16 = I.Cantidad_Db_Dia_16,
           Cantidad_Db_Dia_17 = I.Cantidad_Db_Dia_17,
           Cantidad_Db_Dia_18 = I.Cantidad_Db_Dia_18,
           Cantidad_Db_Dia_19 = I.Cantidad_Db_Dia_19,
           Cantidad_Db_Dia_20 = I.Cantidad_Db_Dia_20,
           Cantidad_Db_Dia_21 = I.Cantidad_Db_Dia_21,
           Cantidad_Db_Dia_22 = I.Cantidad_Db_Dia_22,
           Cantidad_Db_Dia_23 = I.Cantidad_Db_Dia_23,
           Cantidad_Db_Dia_24 = I.Cantidad_Db_Dia_24,
           Cantidad_Db_Dia_25 = I.Cantidad_Db_Dia_25,
           Cantidad_Db_Dia_26 = I.Cantidad_Db_Dia_26,
           Cantidad_Db_Dia_27 = I.Cantidad_Db_Dia_27,
           Cantidad_Db_Dia_28 = I.Cantidad_Db_Dia_28,
           Cantidad_Db_Dia_29 = I.Cantidad_Db_Dia_29,
           Cantidad_Db_Dia_30 = I.Cantidad_Db_Dia_30,
           Cantidad_Db_Dia_31 = I.Cantidad_Db_Dia_31, 
        Total_Db_Dia_1  = I.Total_Db_Dia_1,
           Total_Db_Dia_2  = I.Total_Db_Dia_2,
           Total_Db_Dia_3  = I.Total_Db_Dia_3,
           Total_Db_Dia_4  = I.Total_Db_Dia_4,
           Total_Db_Dia_5  = I.Total_Db_Dia_5,
           Total_Db_Dia_6  = I.Total_Db_Dia_6,
           Total_Db_Dia_7  = I.Total_Db_Dia_7,
           Total_Db_Dia_8  = I.Total_Db_Dia_8,
           Total_Db_Dia_9  = I.Total_Db_Dia_9,
           Total_Db_Dia_10 = I.Total_Db_Dia_10,
           Total_Db_Dia_11 = I.Total_Db_Dia_11,
           Total_Db_Dia_12 = I.Total_Db_Dia_12,
           Total_Db_Dia_13 = I.Total_Db_Dia_13,
           Total_Db_Dia_14 = I.Total_Db_Dia_14,
           Total_Db_Dia_15 = I.Total_Db_Dia_15,
           Total_Db_Dia_16 = I.Total_Db_Dia_16,
           Total_Db_Dia_17 = I.Total_Db_Dia_17,
           Total_Db_Dia_18 = I.Total_Db_Dia_18,
           Total_Db_Dia_19 = I.Total_Db_Dia_19,
           Total_Db_Dia_20 = I.Total_Db_Dia_20,
           Total_Db_Dia_21 = I.Total_Db_Dia_21,
           Total_Db_Dia_22 = I.Total_Db_Dia_22,
           Total_Db_Dia_23 = I.Total_Db_Dia_23,
           Total_Db_Dia_24 = I.Total_Db_Dia_24,
           Total_Db_Dia_25 = I.Total_Db_Dia_25,
           Total_Db_Dia_26 = I.Total_Db_Dia_26,
           Total_Db_Dia_27 = I.Total_Db_Dia_27,
           Total_Db_Dia_28 = I.Total_Db_Dia_28,
           Total_Db_Dia_29 = I.Total_Db_Dia_29,
           Total_Db_Dia_30 = I.Total_Db_Dia_30,
           Total_Db_Dia_31 = I.Total_Db_Dia_31, 
Cantidad_Cr_Dia_1  = I.Cantidad_Cr_Dia_1,
           Cantidad_Cr_Dia_2  = I.Cantidad_Cr_Dia_2,
           Cantidad_Cr_Dia_3  = I.Cantidad_Cr_Dia_3,
           Cantidad_Cr_Dia_4  = I.Cantidad_Cr_Dia_4,
           Cantidad_Cr_Dia_5  = I.Cantidad_Cr_Dia_5,
           Cantidad_Cr_Dia_6  = I.Cantidad_Cr_Dia_6,
           Cantidad_Cr_Dia_7  = I.Cantidad_Cr_Dia_7,
           Cantidad_Cr_Dia_8  = I.Cantidad_Cr_Dia_8,
           Cantidad_Cr_Dia_9  = I.Cantidad_Cr_Dia_9,
           Cantidad_Cr_Dia_10 = I.Cantidad_Cr_Dia_10,
           Cantidad_Cr_Dia_11 = I.Cantidad_Cr_Dia_11,
           Cantidad_Cr_Dia_12 = I.Cantidad_Cr_Dia_12,
           Cantidad_Cr_Dia_13 = I.Cantidad_Cr_Dia_13,
           Cantidad_Cr_Dia_14 = I.Cantidad_Cr_Dia_14,
           Cantidad_Cr_Dia_15 = I.Cantidad_Cr_Dia_15,
           Cantidad_Cr_Dia_16 = I.Cantidad_Cr_Dia_16,
           Cantidad_Cr_Dia_17 = I.Cantidad_Cr_Dia_17,
           Cantidad_Cr_Dia_18 = I.Cantidad_Cr_Dia_18,
           Cantidad_Cr_Dia_19 = I.Cantidad_Cr_Dia_19,
           Cantidad_Cr_Dia_20 = I.Cantidad_Cr_Dia_20,
           Cantidad_Cr_Dia_21 = I.Cantidad_Cr_Dia_21,
           Cantidad_Cr_Dia_22 = I.Cantidad_Cr_Dia_22,
           Cantidad_Cr_Dia_23 = I.Cantidad_Cr_Dia_23,
           Cantidad_Cr_Dia_24 = I.Cantidad_Cr_Dia_24,
           Cantidad_Cr_Dia_25 = I.Cantidad_Cr_Dia_25,
           Cantidad_Cr_Dia_26 = I.Cantidad_Cr_Dia_26,
           Cantidad_Cr_Dia_27 = I.Cantidad_Cr_Dia_27,
           Cantidad_Cr_Dia_28 = I.Cantidad_Cr_Dia_28,
           Cantidad_Cr_Dia_29 = I.Cantidad_Cr_Dia_29,
           Cantidad_Cr_Dia_30 = I.Cantidad_Cr_Dia_30,
           Cantidad_Cr_Dia_31 = I.Cantidad_Cr_Dia_31, 
Total_Cr_Dia_1  = I.Total_Cr_Dia_1,
           Total_Cr_Dia_2  = I.Total_Cr_Dia_2,
           Total_Cr_Dia_3  = I.Total_Cr_Dia_3,
           Total_Cr_Dia_4  = I.Total_Cr_Dia_4,
           Total_Cr_Dia_5  = I.Total_Cr_Dia_5,
           Total_Cr_Dia_6  = I.Total_Cr_Dia_6,
           Total_Cr_Dia_7  = I.Total_Cr_Dia_7,
           Total_Cr_Dia_8  = I.Total_Cr_Dia_8,
           Total_Cr_Dia_9  = I.Total_Cr_Dia_9,
           Total_Cr_Dia_10 = I.Total_Cr_Dia_10,
           Total_Cr_Dia_11 = I.Total_Cr_Dia_11,
           Total_Cr_Dia_12 = I.Total_Cr_Dia_12,
           Total_Cr_Dia_13 = I.Total_Cr_Dia_13,
           Total_Cr_Dia_14 = I.Total_Cr_Dia_14,
           Total_Cr_Dia_15 = I.Total_Cr_Dia_15,
           Total_Cr_Dia_16 = I.Total_Cr_Dia_16,
           Total_Cr_Dia_17 = I.Total_Cr_Dia_17,
           Total_Cr_Dia_18 = I.Total_Cr_Dia_18,
           Total_Cr_Dia_19 = I.Total_Cr_Dia_19,
           Total_Cr_Dia_20 = I.Total_Cr_Dia_20,
           Total_Cr_Dia_21 = I.Total_Cr_Dia_21,
           Total_Cr_Dia_22 = I.Total_Cr_Dia_22,
           Total_Cr_Dia_23 = I.Total_Cr_Dia_23,
           Total_Cr_Dia_24 = I.Total_Cr_Dia_24,
           Total_Cr_Dia_25 = I.Total_Cr_Dia_25,
           Total_Cr_Dia_26 = I.Total_Cr_Dia_26,
           Total_Cr_Dia_27 = I.Total_Cr_Dia_27,
           Total_Cr_Dia_28 = I.Total_Cr_Dia_28,
           Total_Cr_Dia_29 = I.Total_Cr_Dia_29,
           Total_Cr_Dia_30 = I.Total_Cr_Dia_30,
           Total_Cr_Dia_31 = I.Total_Cr_Dia_31 
      WHERE anio = Ln_AnioBase   AND mes = Ln_MesBase       AND codigo_empresa = 1  AND nivel_1 = I.Nivel_1  AND nivel_2 = I.Nivel_2
       AND nivel_3 = I.Nivel_3  AND nivel_4 = I.Nivel_4   AND nivel_5 = I.Nivel_5        AND nivel_6 = I.Nivel_6  AND nivel_7 = I.Nivel_7
       AND nivel_8 = I.Nivel_8;
      IF SQL%NOTFOUND THEN
         INSERT INTO GM_SALDOS_DIARIOS (Codigo_Empresa,Anio,Mes,
         Nivel_1,Nivel_2,Nivel_3,Nivel_4,Nivel_5,Nivel_6,Nivel_7,Nivel_8,
         Cantidad_Db_Dia_1, Cantidad_Db_Dia_2, Cantidad_Db_Dia_3, Cantidad_Db_Dia_4,
         Cantidad_Db_Dia_5, Cantidad_Db_Dia_6, Cantidad_Db_Dia_7, Cantidad_Db_Dia_8,
         Cantidad_Db_Dia_9, Cantidad_Db_Dia_10,Cantidad_Db_Dia_11,Cantidad_Db_Dia_12,
         Cantidad_Db_Dia_13,Cantidad_Db_Dia_14,Cantidad_Db_Dia_15,Cantidad_Db_Dia_16,
         Cantidad_Db_Dia_17,Cantidad_Db_Dia_18,Cantidad_Db_Dia_19,Cantidad_Db_Dia_20,
         Cantidad_Db_Dia_21,Cantidad_Db_Dia_22,Cantidad_Db_Dia_23,Cantidad_Db_Dia_24,
         Cantidad_Db_Dia_25,Cantidad_Db_Dia_26,Cantidad_Db_Dia_27,Cantidad_Db_Dia_28,
         Cantidad_Db_Dia_29,Cantidad_Db_Dia_30,Cantidad_Db_Dia_31,
         Cantidad_Cr_Dia_1, Cantidad_Cr_Dia_2, Cantidad_Cr_Dia_3, Cantidad_Cr_Dia_4,
         Cantidad_Cr_Dia_5, Cantidad_Cr_Dia_6, Cantidad_Cr_Dia_7, Cantidad_Cr_Dia_8,
         Cantidad_Cr_Dia_9, Cantidad_Cr_Dia_10,Cantidad_Cr_Dia_11,Cantidad_Cr_Dia_12,
         Cantidad_Cr_Dia_13,Cantidad_Cr_Dia_14,Cantidad_Cr_Dia_15,Cantidad_Cr_Dia_16,
         Cantidad_Cr_Dia_17,Cantidad_Cr_Dia_18,Cantidad_Cr_Dia_19,Cantidad_Cr_Dia_20,
         Cantidad_Cr_Dia_21,Cantidad_Cr_Dia_22,Cantidad_Cr_Dia_23,Cantidad_Cr_Dia_24,
         Cantidad_Cr_Dia_25,Cantidad_Cr_Dia_26,Cantidad_Cr_Dia_27,Cantidad_Cr_Dia_28,
         Cantidad_Cr_Dia_29,Cantidad_Cr_Dia_30,Cantidad_Cr_Dia_31,
         Total_Db_Dia_1, Total_Db_Dia_2, Total_Db_Dia_3, Total_Db_Dia_4, Total_Db_Dia_5,
         Total_Db_Dia_6, Total_Db_Dia_7, Total_Db_Dia_8, Total_Db_Dia_9, Total_Db_Dia_10,
         Total_Db_Dia_11,Total_Db_Dia_12,Total_Db_Dia_13,Total_Db_Dia_14,Total_Db_Dia_15,
         Total_Db_Dia_16,Total_Db_Dia_17,Total_Db_Dia_18,Total_Db_Dia_19,Total_Db_Dia_20,
         Total_Db_Dia_21,Total_Db_Dia_22,Total_Db_Dia_23,Total_Db_Dia_24,Total_Db_Dia_25,
         Total_Db_Dia_26,Total_Db_Dia_27,Total_Db_Dia_28,Total_Db_Dia_29,Total_Db_Dia_30,
         Total_Db_Dia_31,
            Total_Cr_Dia_1, Total_Cr_Dia_2, Total_Cr_Dia_3, Total_Cr_Dia_4, Total_Cr_Dia_5,
         Total_Cr_Dia_6, Total_Cr_Dia_7, Total_Cr_Dia_8, Total_Cr_Dia_9, Total_Cr_Dia_10,
         Total_Cr_Dia_11,Total_Cr_Dia_12,Total_Cr_Dia_13,Total_Cr_Dia_14,Total_Cr_Dia_15,
         Total_Cr_Dia_16,Total_Cr_Dia_17,Total_Cr_Dia_18,Total_Cr_Dia_19,Total_Cr_Dia_20,
         Total_Cr_Dia_21,Total_Cr_Dia_22,Total_Cr_Dia_23,Total_Cr_Dia_24,Total_Cr_Dia_25,
         Total_Cr_Dia_26,Total_Cr_Dia_27,Total_Cr_Dia_28,Total_Cr_Dia_29,Total_Cr_Dia_30,
         Total_Cr_Dia_31,
         Saldo_Dia_1, Saldo_Dia_2, Saldo_Dia_3, Saldo_Dia_4, Saldo_Dia_5, Saldo_Dia_6,
         Saldo_Dia_7, Saldo_Dia_8, Saldo_Dia_9, Saldo_Dia_10,Saldo_Dia_11,Saldo_Dia_12,
         Saldo_Dia_13,Saldo_Dia_14,Saldo_Dia_15,Saldo_Dia_16,Saldo_Dia_17,Saldo_Dia_18,
         Saldo_Dia_19,Saldo_Dia_20,Saldo_Dia_21,Saldo_Dia_22,Saldo_Dia_23,Saldo_Dia_24,
         Saldo_Dia_25,Saldo_Dia_26,Saldo_Dia_27,Saldo_Dia_28,Saldo_Dia_29,Saldo_Dia_30,
         Saldo_Dia_31, Saldo_Dia_Anterior_Calendario, Saldo_Acumulado_Mensual)
         VALUES (1, Ln_AnioBase, Ln_MesBase, I.Nivel_1,I.Nivel_2,I.Nivel_3,I.Nivel_4,I.Nivel_5,I.Nivel_6,I.Nivel_7,I.Nivel_8,
         I.Cantidad_Db_Dia_1, I.Cantidad_Db_Dia_2, I.Cantidad_Db_Dia_3, I.Cantidad_Db_Dia_4,
         I.Cantidad_Db_Dia_5, I.Cantidad_Db_Dia_6, I.Cantidad_Db_Dia_7, I.Cantidad_Db_Dia_8,
         I.Cantidad_Db_Dia_9, I.Cantidad_Db_Dia_10,I.Cantidad_Db_Dia_11,I.Cantidad_Db_Dia_12,
         I.Cantidad_Db_Dia_13,I.Cantidad_Db_Dia_14,I.Cantidad_Db_Dia_15,I.Cantidad_Db_Dia_16,
         I.Cantidad_Db_Dia_17,I.Cantidad_Db_Dia_18,I.Cantidad_Db_Dia_19,I.Cantidad_Db_Dia_20,
         I.Cantidad_Db_Dia_21,I.Cantidad_Db_Dia_22,I.Cantidad_Db_Dia_23,I.Cantidad_Db_Dia_24,
         I.Cantidad_Db_Dia_25,I.Cantidad_Db_Dia_26,I.Cantidad_Db_Dia_27,I.Cantidad_Db_Dia_28,
         I.Cantidad_Db_Dia_29,I.Cantidad_Db_Dia_30,I.Cantidad_Db_Dia_31,
         I.Cantidad_Cr_Dia_1, I.Cantidad_Cr_Dia_2, I.Cantidad_Cr_Dia_3, I.Cantidad_Cr_Dia_4,
         I.Cantidad_Cr_Dia_5, I.Cantidad_Cr_Dia_6, I.Cantidad_Cr_Dia_7, I.Cantidad_Cr_Dia_8,
         I.Cantidad_Cr_Dia_9, I.Cantidad_Cr_Dia_10,I.Cantidad_Cr_Dia_11,I.Cantidad_Cr_Dia_12,
         I.Cantidad_Cr_Dia_13,I.Cantidad_Cr_Dia_14,I.Cantidad_Cr_Dia_15,I.Cantidad_Cr_Dia_16,
         I.Cantidad_Cr_Dia_17,I.Cantidad_Cr_Dia_18,I.Cantidad_Cr_Dia_19,I.Cantidad_Cr_Dia_20,
         I.Cantidad_Cr_Dia_21,I.Cantidad_Cr_Dia_22,I.Cantidad_Cr_Dia_23,I.Cantidad_Cr_Dia_24,
         I.Cantidad_Cr_Dia_25,I.Cantidad_Cr_Dia_26,I.Cantidad_Cr_Dia_27,I.Cantidad_Cr_Dia_28,
         I.Cantidad_Cr_Dia_29,I.Cantidad_Cr_Dia_30,I.Cantidad_Cr_Dia_31,
         I.Total_Db_Dia_1, I.Total_Db_Dia_2, I.Total_Db_Dia_3, I.Total_Db_Dia_4, I.Total_Db_Dia_5,
         I.Total_Db_Dia_6, I.Total_Db_Dia_7, I.Total_Db_Dia_8, I.Total_Db_Dia_9, I.Total_Db_Dia_10,
         I.Total_Db_Dia_11,I.Total_Db_Dia_12,I.Total_Db_Dia_13,I.Total_Db_Dia_14,I.Total_Db_Dia_15,
         I.Total_Db_Dia_16,I.Total_Db_Dia_17,I.Total_Db_Dia_18,I.Total_Db_Dia_19,I.Total_Db_Dia_20,
         I.Total_Db_Dia_21,I.Total_Db_Dia_22,I.Total_Db_Dia_23,I.Total_Db_Dia_24,I.Total_Db_Dia_25,
         I.Total_Db_Dia_26,I.Total_Db_Dia_27,I.Total_Db_Dia_28,I.Total_Db_Dia_29,I.Total_Db_Dia_30,
         I.Total_Db_Dia_31,
            I.Total_Cr_Dia_1, I.Total_Cr_Dia_2, I.Total_Cr_Dia_3, I.Total_Cr_Dia_4, I.Total_Cr_Dia_5,
         I.Total_Cr_Dia_6, I.Total_Cr_Dia_7, I.Total_Cr_Dia_8, I.Total_Cr_Dia_9, I.Total_Cr_Dia_10,
         I.Total_Cr_Dia_11,I.Total_Cr_Dia_12,I.Total_Cr_Dia_13,I.Total_Cr_Dia_14,I.Total_Cr_Dia_15,
         I.Total_Cr_Dia_16,I.Total_Cr_Dia_17,I.Total_Cr_Dia_18,I.Total_Cr_Dia_19,I.Total_Cr_Dia_20,
         I.Total_Cr_Dia_21,I.Total_Cr_Dia_22,I.Total_Cr_Dia_23,I.Total_Cr_Dia_24,I.Total_Cr_Dia_25,
         I.Total_Cr_Dia_26,I.Total_Cr_Dia_27,I.Total_Cr_Dia_28,I.Total_Cr_Dia_29,I.Total_Cr_Dia_30,
         I.Total_Cr_Dia_31,
         I.Saldo_Dia_1, I.Saldo_Dia_2, I.Saldo_Dia_3, I.Saldo_Dia_4, I.Saldo_Dia_5, I.Saldo_Dia_6,
         I.Saldo_Dia_7, I.Saldo_Dia_8, I.Saldo_Dia_9, I.Saldo_Dia_10,I.Saldo_Dia_11,I.Saldo_Dia_12,
         I.Saldo_Dia_13,I.Saldo_Dia_14,I.Saldo_Dia_15,I.Saldo_Dia_16,I.Saldo_Dia_17,I.Saldo_Dia_18,
         I.Saldo_Dia_19,I.Saldo_Dia_20,I.Saldo_Dia_21,I.Saldo_Dia_22,I.Saldo_Dia_23,I.Saldo_Dia_24,
         I.Saldo_Dia_25,I.Saldo_Dia_26,I.Saldo_Dia_27,I.Saldo_Dia_28,I.Saldo_Dia_29,I.Saldo_Dia_30,
         I.Saldo_Dia_31, I.Saldo_Dia_Anterior_Calendario, I.Saldo_Acumulado_Mensual);
     End if;
   END LOOP;

    
 END;
