DECLARE
  --Lv_NomSec  VARCHAR2(30);
  Ln_MaxVal  NUMBER:=63887;
  Lv_SenSQL  VARCHAR2(1000);
  Ln_Sec     NUMBER;
BEGIN
  Lv_SenSQL := 'BEGIN FOR I IN 1 .. (:Pn_MaxVal + 1) LOOP SELECT MG_S_BITACORA.NEXTVAL INTO :Ln_Sec FROM dual; END LOOP; END;';
  EXECUTE IMMEDIATE Lv_SenSQL USING IN Ln_MaxVal, OUT Ln_Sec; --, :Lv_NomSec;
END;
/

DECLARE
  Ln_Sec     NUMBER;
BEGIN
  FOR i IN 1 .. 9500 LOOP
    SELECT MG_S_BITACORA.NEXTVAL INTO Ln_Sec FROM dual;
  END LOOP;
END;
/