LOAD DATA
   INSERT INTO TABLE numeric_external_test
   (
   a POSITION (1:10) INTEGER EXTERNAL,
   b POSITION (12:21) FLOAT EXTERNAL,
   c POSITION (23:32) DECIMAL EXTERNAL,
   d POSITION (34: 43) ZONED EXTERNAL
   )

